### ISSUE TITLE
what does "grid" mean in your code?

### ISSUE THREAD

**Issue by Li-Shang** [xjqi/GeoNet#3]
I noticed that you read grid from data_dic['grid'], and data_dic is loaded from files which are included in ./list/traindata_grid.txt. But you didn't provide the training data.
So, what does "grid" mean in your code?

Thanks.

**Comment by ChuangbinC** [comment]
@Li-Shang Hi, do you know what is meaning of the "grid"  in this network?

**Comment by xjqi** [comment]
"grid" is to help map the 2D locations to 3D points containing the focal length and camera center. when you replicate the depth map three times in the channel dimension and perform elementwise multiplication with grid, you will get the locations of 3D points.
